### ISSUE TITLE
CSS spillover. Some styles affecting non-elfinder elements

### ISSUE THREAD

**Issue by donShakespeare** [RobiNN1/elFinder-Material-Theme#3]
Things like `input` and other jQueryUi targets are not enclosed as this:
 `.elfinder input{...}` ..., `.elfinder .ui-this{...}`

![image](https://cloud.githubusercontent.com/assets/5103329/26077219/2dbb6eca-3970-11e7-8de1-84f1c0757caf.png)

```css
/**
 * Checkbox
 */
input[type="checkbox"] {
  position: relative;
  border: 0;
  -webkit-appearance: none;
          -moz-appearance: none;
       appearance: none;
  cursor: pointer;
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
  padding: 0;
  margin-bottom: 10px;
}
input[type="checkbox"]:after,
input[type="checkbox"]:focus:after {
  content: "";
  display: block;
  width: 15px;
  height: 15px;
  margin-top: -2px;
  margin-bottom: -6px;
  border: 2px solid #2196f3;
  -webkit-border-radius: 2px;
          border-radius: 2px;
  -webkit-transition: 240ms;
       -o-transition: 240ms;
          transition: 240ms;
}
input[type="checkbox"]:checked:before {
  content: "";
  position: absolute;
  top: 0;
  left: 6px;
  display: table;
  width: 6px;
  height: 12px;
  border: 2px solid #fff;
  border-top-width: 0;
  border-left-width: 0;
  -webkit-transform: rotate(45deg);
      -ms-transform: rotate(45deg);
       -o-transform: rotate(45deg);
          transform: rotate(45deg);
}
input[type="checkbox"]:checked:after {
  background-color: #2196f3;
  border-color: #2196f3;
}
```
